# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: python
python:
  - "3.4"
  - "2.7"
  - "pypy"
 
addons:
  apt:
    sources:
    - tcl
    
addons:
  apt:
    packages:
    - clang
    - gawk
    - tcl
    - autoconf
    - gperf

cache:
  directories:
  - $HOME/yosys
  - $HOME/iverilog

before_install:
  - export PATH=$PATH:$HOME/iverilog/bin/:$HOME/yosys/
  - chmod +x ./scripts/ci/install_iverilog.sh
  - ./scripts/ci/install_iverilog.sh
  - chmod +x ./scripts/ci/install_yosys.sh
  - ./scripts/ci/install_yosys.sh
  
# command to install dependencies
install:
  - chmod +x ./scripts/ci/install_myhdl.sh
  - ./scripts/ci/install_myhdl.sh
  - pip install coverage
  - pip install coveralls
  - pip install Pillow
  - pip install .

# run the test, nosetests can be used
script:
   - cd examples
   - py.test   # -s
   - cd ../test
   - py.test   # -s

notifications:
  email: false
